/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * RealWorld Conduit API
 * Conduit API documentation
 * OpenAPI spec version: 1.0.0
 */
import { HttpClient } from "@angular/common/http";
import type { HttpResponse as AngularHttpResponse, HttpContext, HttpEvent, HttpHeaders, HttpParams } from "@angular/common/http";

import { Injectable } from "@angular/core";

import type { Observable } from "rxjs";

import type { ProfileResponseResponse } from "../../model";

type HttpClientOptions = {
	headers?:
		| HttpHeaders
		| {
				[header: string]: string | string[];
		  };
	context?: HttpContext;
	observe?: any;
	params?:
		| HttpParams
		| {
				[param: string]: string | number | boolean | ReadonlyArray<string | number | boolean>;
		  };
	reportProgress?: boolean;
	responseType?: any;
	withCredentials?: boolean;
};

@Injectable({ providedIn: "root" })
export class ProfileService {
	constructor(private http: HttpClient) {} /**
	 * Get a profile of a user of the system. Auth is optional
	 * @summary Get a profile
	 */
	getProfileByUsername<TData = ProfileResponseResponse>(
		username: string,
		options?: Omit<HttpClientOptions, "observe"> & { observe?: "body" },
	): Observable<TData>;
	getProfileByUsername<TData = ProfileResponseResponse>(
		username: string,
		options?: Omit<HttpClientOptions, "observe"> & { observe?: "response" },
	): Observable<AngularHttpResponse<TData>>;
	getProfileByUsername<TData = ProfileResponseResponse>(
		username: string,
		options?: Omit<HttpClientOptions, "observe"> & { observe?: "events" },
	): Observable<HttpEvent<TData>>;
	getProfileByUsername<TData = ProfileResponseResponse>(username: string, options?: HttpClientOptions): Observable<TData> {
		return this.http.get<TData>(`/profiles/${username}`, options);
	}
	/**
	 * Follow a user by username
	 * @summary Follow a user
	 */
	followUserByUsername<TData = ProfileResponseResponse>(
		username: string,
		options?: Omit<HttpClientOptions, "observe"> & { observe?: "body" },
	): Observable<TData>;
	followUserByUsername<TData = ProfileResponseResponse>(
		username: string,
		options?: Omit<HttpClientOptions, "observe"> & { observe?: "response" },
	): Observable<AngularHttpResponse<TData>>;
	followUserByUsername<TData = ProfileResponseResponse>(
		username: string,
		options?: Omit<HttpClientOptions, "observe"> & { observe?: "events" },
	): Observable<HttpEvent<TData>>;
	followUserByUsername<TData = ProfileResponseResponse>(username: string, options?: HttpClientOptions): Observable<TData> {
		return this.http.post<TData>(`/profiles/${username}/follow`, undefined, options);
	}
	/**
	 * Unfollow a user by username
	 * @summary Unfollow a user
	 */
	unfollowUserByUsername<TData = ProfileResponseResponse>(
		username: string,
		options?: Omit<HttpClientOptions, "observe"> & { observe?: "body" },
	): Observable<TData>;
	unfollowUserByUsername<TData = ProfileResponseResponse>(
		username: string,
		options?: Omit<HttpClientOptions, "observe"> & { observe?: "response" },
	): Observable<AngularHttpResponse<TData>>;
	unfollowUserByUsername<TData = ProfileResponseResponse>(
		username: string,
		options?: Omit<HttpClientOptions, "observe"> & { observe?: "events" },
	): Observable<HttpEvent<TData>>;
	unfollowUserByUsername<TData = ProfileResponseResponse>(username: string, options?: HttpClientOptions): Observable<TData> {
		return this.http.delete<TData>(`/profiles/${username}/follow`, options);
	}
}

export type GetProfileByUsernameClientResult = NonNullable<ProfileResponseResponse>;
export type FollowUserByUsernameClientResult = NonNullable<ProfileResponseResponse>;
export type UnfollowUserByUsernameClientResult = NonNullable<ProfileResponseResponse>;
