import type { LimitParamParameter } from "./limitParamParameter";
/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * RealWorld Conduit API
 * Conduit API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { OffsetParamParameter } from "./offsetParamParameter";

export type GetArticlesParams = {
	/**
	 * Filter by tag
	 */
	tag?: string;
	/**
	 * Filter by author (username)
	 */
	author?: string;
	/**
	 * Filter by favorites of a user (username)
	 */
	favorited?: string;
	/**
	 * The number of items to skip before starting to collect the result set.
	 */
	offset?: OffsetParamParameter;
	/**
	 * The numbers of items to return.
	 */
	limit?: LimitParamParameter;
};
