import type { LimitParamParameter } from "./limitParamParameter";
/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * RealWorld Conduit API
 * Conduit API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { OffsetParamParameter } from "./offsetParamParameter";

export type GetArticlesFeedParams = {
	/**
	 * The number of items to skip before starting to collect the result set.
	 */
	offset?: OffsetParamParameter;
	/**
	 * The numbers of items to return.
	 */
	limit?: LimitParamParameter;
};
