/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * RealWorld Conduit API
 * Conduit API documentation
 * OpenAPI spec version: 1.0.0
 */

/**
 * The numbers of items to return.
 */
export type LimitParamParameter = number;
