/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * RealWorld Conduit API
 * Conduit API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { LoginUser } from "./loginUser";

export type LoginUserRequestBody = {
	user: LoginUser;
};
