/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * RealWorld Conduit API
 * Conduit API documentation
 * OpenAPI spec version: 1.0.0
 */

/**
 * The number of items to skip before starting to collect the result set.
 */
export type OffsetParamParameter = number;
